### ISSUE TITLE
v0.X.0 - Interactive Frames

### ISSUE THREAD

**Issue by SamuelLHuber** [dtechvision/expocaster#3]
# Support Interactive Frames

support [full frame spec](https://docs.farcaster.xyz/reference/frames/spec) and it's interactions by leveraging a signer for the interacting user.

## TODOs

- [ ] Signer Management
  - [ ] Register Signer: create UI to register signer (equivalent to sign up)
      - should use Auth Functions and user hooks already built in [farcasterkit](https://github.com/dtechvision/farcasterkit) 
      - [ ] Sign in with Warpcast [authkit](https://docs.farcaster.xyz/auth-kit/introduction)
      - [ ] Sign in with Ethereum Wallet 
  - [ ] Manage Signers on Backend (Supabase or other?) in sample Expocaster App - users are free to change
      - should use Auth Functions and user hooks already built in [farcasterkit](https://github.com/dtechvision/farcasterkit) 
      - [ ] in Profile page UI support deleting account (revoking signer) - note: adding already done with register signer
- [ ] Frame Interaction
  - [ ] Support full [Frame Spec](https://docs.farcaster.xyz/reference/frames/spec) of Interactions
